let disneyRides = [
  {
    id: 1,
    img: "/../../public/Disney/astro-orbiter-00.webp",
    name:"Astro Orbiter",
    category: "ride",
    description: "Rockets revolving around a central axis",
    duration: 1.5,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 2,
    name:"Barnstormer",
    category: "ride",
    description: "Junior roller coaster",
    duration: 2,
    heightRequirement: "35in",
    lightningLane: false,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 3,
    name:"Big Thunder Mountain Railroad",
    category: "ride",
    description: "Tame, western mining themed roller coaster",
    duration: 7,
    heightRequirement: "40in",
    lightningLane: true,
    location: "Frontierland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 4,
    name:"Buzz Lightyear's Space Ranger Spin",
    category: "ride",
    description: "Whimsical space travel-themed indoor ride",
    duration: 4.5,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 5,
    name:"Casey Jr. Splash 'N' Soak Station",
    category: "water play area",
    description: "Opportunity to get wet",
    duration: 0,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Fantasyland",
    openVeryMerry: false,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 6,
    name:"Country Bear Jamboree",
    category: "show",
    description: "Audioanimatronic country-hoedown theater show",
    duration: 10,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Adventureland",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 7,
    name:"Dumbo the Flying Elephant",
    category: "ride",
    description: "",
    duration: 0,
    heightRequirement: "",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 8,
    name:"Enchanted Tales with Belle",
    category: "show",
    description: "Interactive Character Show",
    duration: 20,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 9,
    name:"Frontierland Shootin' Arcade",
    category: "arcade",
    description: "Electronic shooting gallery",
    duration: 3,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Frontierland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: false
  },
  {
    id: 10,
    name:"The Hall of Presidents",
    category: "show",
    description: "Audioanimatronic historical theater presentation",
    duration: 23,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Liberty Square",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 11,
    name:"The Haunted Mansion",
    category: "ride",
    description: "Haunted house dark ride",
    duration: 10,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Liberty Square",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 12,
    name:"it's a small world",
    category: "ride",
    description: "World-brotherhood-themed indoor boat ride",
    duration: 14,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 13,
    name:"Jungle Cruise",
    category: "ride",
    description: "Outdoor safari-themed boat-ride adventure",
    duration: 8,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Adventureland",
    openVeryMerry: true,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 14,
    name:"Liberty Square Riverboat",
    category: "ride",
    description: "Outdoor scenic boat ride",
    duration: 16,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Liberty Square",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 15,
    name:"Mad Tea Party",
    category: "ride",
    description: "Midway-type spinning ride",
    duration: 1.5,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 16,
    name:"The Magic Carpets of Aladdin",
    category: "ride",
    description: "Elaborate midway ride",
    duration: 1.5,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Adventureland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 17,
    name:"The Many Adventures of Winnie the Pooh",
    category: "ride",
    description: "Indoor track ride",
    duration: 4,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 18,
    name:"Mickey's PhilharMagic",
    category: "show",
    description: "3-D movie",
    duration: 12,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 19,
    name:"Monsters Inc. Laugh Floor",
    category: "show",
    description: "Interactive animated comedy routines",
    duration: 15,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: false
  },
  {
    id: 20,
    name:"Peter Pan's Flight",
    category: "ride",
    description: "Indoor track ride",
    duration: 3,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 21,
    name:"Pirates of the Caribbean",
    category: "ride",
    description: "Indoor pirate-themed boat ride",
    duration: 7.5,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Adventureland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 22,
    name:"Prince Charming Regal Carrousel",
    category: "ride",
    description: "Merry-go-round",
    duration: 2,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 23,
    name:"Seven Dwarfs Mine Train",
    category: "ride",
    description: "Indoor/outdoor roller coaster",
    duration: 3,
    heightRequirement: "38",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 24,
    name:"Space Mountain",
    category: "ride",
    description: "Roller coaster in the dark",
    duration: 2.5,
    heightRequirement: "44",
    lightningLane: true,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 25,
    name:"Swiss Family Treehouse",
    category: "walkthrough",
    description: "Outdoor walk-through treehouse",
    duration: 12.5,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Adventureland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 26,
    name:"Tom Sawyer Island",
    category: "ride",
    description: "Outdoor walk-through exhibit and rustic playground",
    duration: 30,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Frontierland",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: true
  },
  {
    id: 27,
    name:"Tomorrowland Speedway",
    category: "ride",
    description: "Drive-'em yourself miniature cars",
    duration: 4.25,
    heightRequirement: "32",
    lightningLane: true,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 28,
    name:"Tomorrowland Transit Authority PeopleMover",
    category: "ride",
    description: "Scenic tour of Tomorrowland",
    duration: 10,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 29,
    name:"TRON Lightcycle/Run",
    category: "ride",
    description: "A fast, indoor/outdoor rollercoaster",
    duration: 2,
    heightRequirement: "48",
    lightningLane: true,
    location: "Tomorrowland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 30,
    img: "",
    name:"Under the Sea - Journey of The Little Mermaid",
    category: "ride",
    description: "Track ride in the dark",
    duration: 7,
    heightRequirement: "N/A",
    lightningLane: true,
    location: "Fantasyland",
    openVeryMerry: true,
    openNotSoScary: true,
    wheelchairTransfer: true
  },
  {
    id: 31,
    name:"Walt Disney World Railroad",
    category: "ride",
    description: "Scenic railroad ride around the perimeter of the Magic Kingdom, and transportation to Frontierland and Fantasyland",
    duration: 20,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Main Street U.S.A.",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: true
  },
  {
    id: 32,
    name:"Walt Disney's Carousel of Progress",
    category: "show",
    description: "Audioanimatronic theater production",
    duration: 21,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Tomorrowland",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  },
  {
    id: 33,
    name:"Walt Disney's Enchanted Tiki Room",
    category: "show",
    description: "Audioanimatronic Pacific- island musical-theater show",
    duration: 15.5,
    heightRequirement: "N/A",
    lightningLane: false,
    location: "Adventureland",
    openVeryMerry: false,
    openNotSoScary: false,
    wheelchairTransfer: false
  }
]

export default disneyRides